name = "TermSymbols"
uuid = "eda0e949-db46-4898-b47c-29e4a0fc86ae"
authors = ["gustavojra <gustavo.aroeira@gmail.com>"]
version = "0.1.0"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
